### ISSUE TITLE
create the core bundle in a bundles folder

### ISSUE THREAD

**Issue by bhellema** [Adobe-Consulting-Services/lazybones-aem-templates#14]
To provide best practices it might be nice to have the core bundle created under a bundles folder such that additional bundles can be located in this directory as well.   A use case might be that an API bundle is required and a core bundle, therefore to provide some project organization have all bundles created within a bundles folder.

```
+ project
   + bundles
      - core
      - api
   + content
    ....
```

**Comment by justinedelson** [comment]
@bhellema do you typically see a pom.xml in the bundles directory in these cases?

**Comment by bhellema** [comment]
I don't think it would provide any benefit having it there.

**Comment by justinedelson** [comment]
ok. then this is much simpler than I originally thought.

**Comment by justinedelson** [comment]
version 0.0.36 has been released with this change
