### ISSUE TITLE
Include package icon for Lazybones

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/lazybones-aem-templates#24]
WDYT about including a "custom" package icon for lazybone generated apps? This has 2 advantages: 
1) Helps quickly visually identify your app packages in package manager (since pretty much everything uses the default package icon)
2) Makes it trivial to update the thumbnail to a project specific image; swap out the `thumbnail.png` and you dont have to worry about the maven configs.

I made 3 simple options if any suit your fancy. Im partial to the paper airplane, but I like a but of whimsy in my tech too. 

If there are icons for the CoralUI set [1] that would work better, just let me know which and i can generate a new icon super quick.

![plane](https://cloud.githubusercontent.com/assets/1451868/20739741/4d62b6ec-b68b-11e6-9e40-ce99f86f203d.png)
![rocket](https://cloud.githubusercontent.com/assets/1451868/20739740/4d62a6b6-b68b-11e6-9596-ca6aa91a9ef1.png)
![stacks](https://cloud.githubusercontent.com/assets/1451868/20739742/4d63927e-b68b-11e6-9d88-f10fa1d700f4.png)

[1] https://docs.adobe.com/content/docs/en/aem/6-0/develop/ref/coral-ui/docs/2.1.2-aem600-015/icon.html

**Comment by justinedelson** [comment]
I don't think it is a recommended/allowed practice to use Coral icons for non-Adobe projects (which I suspect is the majority of the cases for this lazybones template, although certainly it is used by, among others, me, to generate Adobe-branded icons).

Are you thinking that the template lets you select amongst these three choices? Or provide a custom one? Or both?

**Comment by davidjgonzalez** [comment]
@justinedelson ah - i thought CUI icons could be used as part of Adobe projects. I can look around for an open source icon set w/ a similar aesthetic.

The initial thought was having a single default thumbnail (for simplicity more than anything), but i suppose there could be a input that allows icon selection. IMO the value is the readily identifiable visual in package manager, and differentiating *my* packages from product packages.

A convo for a different thread, but we should figure out if the CUI icon restrictions requires a re-work of the ACS Commons ACL Packager icons which are CUI based.

**Comment by justinedelson** [comment]
I'm more concerned about actual customers using this template to create their packages. In that case, if I'm a developer at FunCo, it wouldn't make sense to use a CUI icon. I want to use a FunCo icon :)

Maybe the answer is to make the default icon for lazybones-generated projects this image: http://lazybonessmokehouse.net/wp-content/uploads/2016/01/logo.png

I'm sure if we asked nicely, they'd let us use it :)

**Comment by davidjgonzalez** [comment]
Out of sight, out of mind. Having a generic pulls in into mind, and (as noted in value prop 2 above) makes it trivial to update the icon to a FunCo logo (the hardest part is finding a 64x64 FunCo logo). 

IMO the the package icons ordered best to worst are:

1) A FunCo icon
2) A generic icon that is NOT the default blue cube (Dont care what it is, ideally invokes some sense of an application)
3) The default blue cube

**Comment by davidjgonzalez** [comment]
![change-me](https://cloud.githubusercontent.com/assets/1451868/20777579/ee8f4c10-b735-11e6-8aa5-ab80fc3cddcf.png)

Found the perfect one!
