### ISSUE TITLE
Bintray generates an HTTP 401

### ISSUE THREAD

**Issue by sasconsul** [Adobe-Consulting-Services/lazybones-aem-templates#26]
Using the following commands on Mac OS X, I got an HTTP 401 (unauthorized):

    export PATH=$PATH:~/devenv/lazybones-0.8.3/bin/
    lazybones create aem-multimodule-project aemtraining

It seemed that Bintray wants a username and password.

FYI: I was following the article http://www.aemcq5tutorials.com/tutorials/create-aem-project-structure-using-lazybones

**Comment by justinedelson** [comment]
you'll have to take this up with whomever wrote that blog.
