### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by himanshu-pathak** [Adobe-Consulting-Services/lazybones-aem-templates#30]
Tried this today and found it really awesome. A few improvements i could think of.
Wizard:

- Would be better to ask for 'project code' and than use it everywhere rather than suggesting the default 'my'. For some options its already working but not consistent. 
- Maven artifact ID for the generated reactor project [example-project]:  this could use the 'prject code as suggested above.'
- Would you like to create AEM 6.2 Editable Templates folders? [yes]: Can be rewritten as Would you like to create Editable Templates folders? [yes]: (we have now 6.3 as well. better if this option is dynamic based on the version selection so this only appears if the version is >=6.2)
- 

Pom.xml

- commons-lang can be dropped in favor of commons-lang3
- jsp-api should be removed to encourage HTL
- Jcr should be dropped to encourage aem/resource api
- com.day.cq api should be removed as these should be part of uber
- org.apache.sling should be removed as these should be part of uber
- com.day.commons should be removed
- For the newer versions org.apache.felix.scr.annotations should be removed to encourage osgi annotations

**Comment by hemanth415** [comment]
I'm currently setting up a new project. On my way of doing this, I have couple of observation 

- I see two dependencies in the pom related to Apache Commons. The older one can be removed I guess. 

```
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.0.1</version>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>commons-lang</groupId>
    <artifactId>commons-lang</artifactId>
    <version>2.5</version>
    <scope>provided</scope>
</dependency>
```

- The  Apache Felix SCR annotations are deprecated in AEM 6.3, so going forward new OSGi R6 annotations API would be used. It would be nice if the pom is updated with newer annotations API while project creation. 

https://forums.adobe.com/message/9545513#

https://helpx.adobe.com/experience-manager/kt/platform-repository/using/aem-6-3-article-develop.html#Mavendependenciesandplugins

Thanks.

**Comment by justinedelson** [comment]
please create individual issues rather than these kinds of broad buckets.

Most of these seem valid. The only thing I would say is that while it is all find and good to push to HTL, the reality is that JSPs are still quite prevalent, so the changes which break JSP code-completion in the IDE are IMO non-starters (and really have no value in doing so).

**Comment by hemanth415** [comment]
@justinedelson -  I would be creating a new issue.

Thanks.
