### ISSUE TITLE
Remove support for AEM 5.6.1, 6.0, 6.1, and 6.2

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/lazybones-aem-templates#32]
In looking at some of the desired changes (like #31), it would help simplify things significantly if we could drop support for 5.6.1, 6.0, 6.1, and 6.2. I can't imagine there is a lot of interest in creating *new* projects for these old versions.

**Comment by ireasor** [comment]
I would actually classify creating a new project for 6.0 or 6.1 as a worst practice ;)

**Comment by davidjgonzalez** [comment]
+1 to dropping support of 6.0/6.1. The future is now.

Could you cut a template of the project as it stands today (with no future maintance) that supports the older versions? (Iirc you did something like this for summit?)

**Comment by sachioross** [comment]
+1 for dropping support for 6.0/6.1. I'm seeing more projects that are AMS deals which means it'll be the latest major release in addition to what Ian and David mentioned.

Also, really like @davidjgonzalez suggestion: if you could do a release for lazybones as it stands today then it still leaves a version of lazybones that people _could_ use if they really needed to.

**Comment by joerghoh** [comment]
+1 for dropping support for 6.0/6.1

**Comment by justinedelson** [comment]
@ireasor nah, a worst practice would be creating a new project for CQ 4 :)

@davidjgonzalez @sachioross you can specify the template version on the command line like

    lazybones create aem-multimodule-project 0.0.38 my-project

When making this change, it would probably make sense to add that information to the README.

**Comment by badvision** [comment]
👍 Get with the now, people!  (drop 'em!)
