### ISSUE TITLE
Mark this project as deprecated?

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/lazybones-aem-templates#45]
@justinedelson should this project be marked as deprecated, and point people to https://github.com/adobe/aem-project-archetype ?

It seems like the lack of alignment to Cloud Manager/AEM as a Cloud Service is more of a detriment than the boon provided by all its bells and whistles. 

WDYT?

**Comment by badvision** [comment]
I think that is most wise.  There are a few things about this archetype that I rather like, but we would do best to converge on one standard and contribute to that single archetype to make improvements as needed.  Before we erect a gravestone for this template, we should at least do a postmortem on what areas it addresses better/differently than the aem project archetype.

**Comment by davidjgonzalez** [comment]
Should we archive this Github project as well? Just to help make it clear? (im the type of person that could very well miss that line in the readme)

**Comment by justinedelson** [comment]
Agreed...

* updated readme
* added topics deprecated and obsolete
* changed project description

Regarding @badvision 's comment on a "postmortem" that should probably happen in the aem-project-archetype project
