### ISSUE TITLE
Can't build with 6.1 uber.jar when org.apache.sling.api.servlets.SlingAllMethodsServlet is used

### ISSUE THREAD

**Issue by andre-inside** [Adobe-Consulting-Services/lazybones-aem-templates#8]
When i create a new project with AEM 6.1 and then create a new Servlet which extends from SlingSafeMethodsServlet the build fails. 
---------------------
[INFO] My AEM Project - Reactor Project .................. SUCCESS [  0.284 s]
[INFO] My AEM Project Bundle ............................. FAILURE [  2.970 s]
[INFO] My AEM Project Content Package .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.442 s
[INFO] Finished at: 2015-06-05T13:47:50+01:00
[INFO] Final Memory: 23M/228M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.felix:maven-scr-plugin:1.20.0:scr (generate-scr-descriptor) on project example-project-bundle: Execution generate-scr-descriptor of goal org.apache.felix:maven-scr-plugin:1.20.0:scr failed: An API incompatibility was encountered while executing org.apache.felix:maven-scr-plugin:1.20.0:scr: java.lang.VerifyError: Constructor must call super() or this() before return
[ERROR] Exception Details:
[ERROR] Location:
[ERROR] org/apache/sling/api/servlets/SlingSafeMethodsServlet.<init>()V @1: return
[ERROR] Reason:
[ERROR] Error exists in the bytecode
[ERROR] Bytecode:
[ERROR] 0000000: 2ab1
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.felix:maven-scr-plugin:1.20.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/andrecrettaz/.m2/repository/org/apache/felix/maven-scr-plugin/1.20.0/maven-scr-plugin-1.20.0.jar
[ERROR] urls[1] = file:/Users/andrecrettaz/.m2/repository/org/apache/maven/maven-archiver/2.2/maven-archiver-2.2.jar
[ERROR] urls[2] = file:/Users/andrecrettaz/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[3] = file:/Users/andrecrettaz/.m2/repository/org/codehaus/plexus/plexus-archiver/1.0-alpha-7/plexus-archiver-1.0-alpha-7.jar
[ERROR] urls[4] = file:/Users/andrecrettaz/.m2/repository/org/apache/felix/org.apache.felix.scr.generator/1.12.0/org.apache.felix.scr.generator-1.12.0.jar
[ERROR] urls[5] = file:/Users/andrecrettaz/.m2/repository/org/ow2/asm/asm-all/5.0.2/asm-all-5.0.2.jar
[ERROR] urls[6] = file:/Users/andrecrettaz/.m2/repository/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.jar
[ERROR] urls[7] = file:/Users/andrecrettaz/.m2/repository/org/osgi/org.osgi.compendium/4.2.0/org.osgi.compendium-4.2.0.jar
[ERROR] urls[8] = file:/Users/andrecrettaz/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[9] = file:/Users/andrecrettaz/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.myco:example-project-bundle:0.0.1-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
---------------------

I fixed it by explizitly defining:

<dependency>
	<groupId>org.apache.sling</groupId>
	<artifactId>org.apache.sling.api</artifactId>
	<version>2.9.0</version>
	<scope>provided</scope>
</dependency>

in the pom.xml

(i know it is not really a issue with the lazybones template, but just wanted inform you that this issue exists)

**Comment by mskalicky** [comment]
I am getting the same exact errors but I already have the sling.api dependency in the pom file. I get the errors with or without the sling-api dependency.  I've tried deleting repository in .m2.  I've updated all of the dependency versions and plugin versions.  I don't really know what else to try.  I'd appreciate any thoughts anyone could provide.

**Comment by justinedelson** [comment]
@mskalicky what is the size of ~/.m2/repository/com/adobe/aem/uber-jar/6.1.0/uber-jar-6.1.0-obfuscated-apis.jar

**Comment by mskalicky** [comment]
Size of ~/.m2/repository/com/adobe/aem/uber-jar/6.1.0 is 14180751

**Comment by mskalicky** [comment]
Justin,
Thank you for response.  I see that this size is correct. I did the checksum and it checks out, too.  I just created a new post on the Adobe AEM forum to see if anyone else has ideas.
Again, thank you for responding to my question.
Mary

**Comment by krassib** [comment]
Hi All,

I am also facing the exact same problem.
		<dependency>
			<groupId>com.adobe.aem</groupId>
			<artifactId>uber-jar</artifactId>
			<version>6.1.0</version>
			<scope>provided</scope>
			<classifier>obfuscated-apis</classifier>
		</dependency>

Errors log from maven build listed below:

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.felix:maven-scr-plugin:1.20.0:scr (generate-scr-scrdescriptor) on project kp-foundation.core: Execution generate-scr-scrdescriptor of goal org.apache.felix:maven-scr-plugin:1.20.0:scr failed: An API incompatibility was encountered while executing org.apache.felix:maven-scr-plugin:1.20.0:scr: java.lang.VerifyError: Constructor must call super() or this() before return
[ERROR] Exception Details:
[ERROR] Location:
[ERROR] com/adobe/cq/sightly/WCMUsePojo.<init>()V @1: return
[ERROR] Reason:
[ERROR] Error exists in the bytecode
[ERROR] Bytecode:
[ERROR] 0x0000000: 2ab1
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.felix:maven-scr-plugin:1.20.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/krassimir.boyanov/.m2/repository/org/apache/felix/maven-scr-plugin/1.20.0/maven-scr-plugin-1.20.0.jar
[ERROR] urls[1] = file:/C:/Users/krassimir.boyanov/.m2/repository/org/slf4j/slf4j-simple/1.5.11/slf4j-simple-1.5.11.jar
[ERROR] urls[2] = file:/C:/Users/krassimir.boyanov/.m2/repository/org/apache/maven/maven-archiver/2.2/maven-archiver-2.2.jar
[ERROR] urls[3] = file:/C:/Users/krassimir.boyanov/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[4] = file:/C:/Users/krassimir.boyanov/.m2/repository/org/codehaus/plexus/plexus-archiver/1.0-alpha-7/plexus-archiver-1.0-alpha-7.jar
[ERROR] urls[5] = file:/C:/Users/krassimir.boyanov/.m2/repository/org/apache/felix/org.apache.felix.scr.generator/1.12.0/org.apache.felix.scr.generator-1.12.0.jar
[ERROR] urls[6] = file:/C:/Users/krassimir.boyanov/.m2/repository/org/ow2/asm/asm-all/5.0.2/asm-all-5.0.2.jar
[ERROR] urls[7] = file:/C:/Users/krassimir.boyanov/.m2/repository/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.jar
[ERROR] urls[8] = file:/C:/Users/krassimir.boyanov/.m2/repository/org/osgi/org.osgi.compendium/4.2.0/org.osgi.compendium-4.2.0.jar
[ERROR] urls[9] = file:/C:/Users/krassimir.boyanov/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[10] = file:/C:/Users/krassimir.boyanov/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.kp.foundation:kp-foundation.core:DEV-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------

Thanks,
Krassimir

**Comment by yogeshkaliyarajan** [comment]
Hi All-
I am also facing the exact same problem when using SP1 jar.

<dependency>
    			<groupId>com.adobe.aem</groupId>
    			<artifactId>uber-jar</artifactId>
    			<version>6.1.0-SP1-load1</version>
                        <scope>provided</scope>
</dependency>

Thanks, Yogi

**Comment by yogeshkaliyarajan** [comment]
Error log for 6.1 SP1 jar

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.felix:maven-scr-plugin:1.17.0:scr (generate-scr-scrdescriptor) on project: 
Execution generate-scr-scrdescriptor of goal org.apache.felix:maven-scr-plugin:1.17.0:scr failed: An API incompatibility 
was encountered while executing org.apache.felix:maven-scr-plugin:1.17.0:scr: java.lang.VerifyError: 
Constructor must call super() or this() before return
[ERROR] Exception Details:
[ERROR] Location:
[ERROR] org/apache/sling/api/servlets/SlingSafeMethodsServlet.<init>()V @1: return
[ERROR] Reason:
[ERROR] Error exists in the bytecode
[ERROR] Bytecode:
[ERROR] 0x0000000: 2ab1
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.felix:maven-scr-plugin:1.17.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/test/.m2/repository/org/apache/felix/maven-scr-plugin/1.17.0/maven-scr-plugin-1.17.0.jar
[ERROR] urls[1] = file:/C:/Users/test/.m2/repository/org/slf4j/slf4j-simple/1.5.11/slf4j-simple-1.5.11.jar
[ERROR] urls[2] = file:/C:/Users/test/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar
[ERROR] urls[3] = file:/C:/Users/test/.m2/repository/ch/qos/logback/logback-core/1.1.3/logback-core-1.1.3.jar
[ERROR] urls[4] = file:/C:/Users/test/.m2/repository/org/apache/maven/maven-archiver/2.2/maven-archiver-2.2.jar
[ERROR] urls[5] = file:/C:/Users/test/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[6] = file:/C:/Users/test/.m2/repository/org/codehaus/plexus/plexus-archiver/1.0-alpha-7/plexus-archiver-1.0-alpha-7.jar
[ERROR] urls[7] = file:/C:/Users/test/.m2/repository/org/apache/felix/org.apache.felix.scr.generator/1.10.0/org.apache.felix.scr.generator-1.10.0.jar
[ERROR] urls[8] = file:/C:/Users/test/.m2/repository/org/ow2/asm/asm-all/5.0.2/asm-all-5.0.2.jar
[ERROR] urls[9] = file:/C:/Users/test/.m2/repository/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.jar
[ERROR] urls[10] = file:/C:/Users/test/.m2/repository/org/osgi/org.osgi.compendium/4.2.0/org.osgi.compendium-4.2.0.jar
[ERROR] urls[11] = file:/C:/Users/test/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.
jar
[ERROR] urls[12] = file:/C:/Users/test/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
[ERROR] Number of foreign imports: 1

**Comment by justinedelson** [comment]
This is an issue with the uberjar, not the template. You may need the unobfuscated version.

**Comment by yogeshkaliyarajan** [comment]
@justinedelson ,
Thanks for your quick response.

I would like to know classifier name for unobfuscated version. I have mentioned the below dependency in my pom.xml. and also looked at Adobe public repository for unobfuscated version. This is no such type of jar in https://repo.adobe.com/nexus/content/groups/public/com/adobe/aem/uber-jar/6.1.0-SP1-load1/

                      <dependency>
				<groupId>com.adobe.aem</groupId>
				<artifactId>uber-jar</artifactId>
				<version>6.1.0-SP1-load1</version>
				<classifier>unobfuscated-apis</classifier>
				<scope>provided</scope>
			</dependency> 

Please provide me your valuable inputs for my issue.

Thanks in Advance.

**Comment by yogeshkaliyarajan** [comment]
Adobe produces two different versions of the UberJar. There is an obsfucated version available on
https://repo.adobe.com/ without any authentication requirement. This is easy to access and meets many needs.
Adobe also makes an unobsfucated version available to customers and partners upon request. To request this
version, customers and partners need to create a DayCare ticket. They will provide you with the unobsfucated UberJar.
Ideally, you will then deploy this onto a Maven Repository Manager private to your company, but it may be distributed
to individual developers if necessary.

The obfuscated version serves most of the common use cases seen in AEM development. The unobfuscated version is, however,
necessary in a few scenarios:
* Extending a concrete or abstract base class in the AEM API where the extended class either has SCR annotations or is used in a unit test (or both)
* Unit testing a class which uses a class or static method from the AEM API.

There are two branches:
* `obfuscated` - uses the obfuscated version and includes a test showing simple mocking of an AEM service interface.
* `unobfuscated` - uses the unobfuscated version and includes a class extending an abstract base class and unit tests leveraging methods from the API.

**Comment by yogeshkaliyarajan** [comment]
I have received AEM 6.1 SP1 Uber Jar unobfuscated version from Adobe thru DayCare ticket. 

We are getting below error...Please provide me your valuable inputs.

 [WARNING] Bundle com.test:test-service:bundle:1.0-SNAPSHOT : No translation found for macro: range;[==,+)
[ERROR] Bundle com.test:test-service:bundle:1.0-SNAPSHOT : Invalid syntax for version: null, for cmd: range, a
rguments; [range, [==,+)]
[ERROR] Bundle com.test:test-service:bundle:1.0-SNAPSHOT : Invalid syntax for version: [2.6,3), for cmd: range
, arguments; [range, [==,+)]
[ERROR] Error(s) found in bundle configuration

[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:3.0.0:bundle (default-bundle) on project com.test:test-service: 
Error(s) found in bundle configuration -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.felix:maven-bundle-plugin:3.0.
0:bundle (default-bundle) on project test-service: Error(s) found in bundle configuration
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.
java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error(s) found in bundle configuration
        at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:441)
        at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:288)
        at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:279)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: org.apache.maven.plugin.MojoFailureException: Error(s) found in bundle configuration
        at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:380)
        ... 23 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :test-service

**Comment by thcharan** [comment]
Hi, Was there any solution here - I couldn't create JMX Mbeans due to this issue. Amy thoughts on workaround?

**Comment by justinedelson** [comment]
this issue is closed. I'd suggest opening new issue(s) if you have unrelated problems.

**Comment by dileepagit** [comment]
Following worked for me.
`<dependency>
				<groupId>com.adobe.aem</groupId>
				<artifactId>aem-api</artifactId>
				<version>6.0.0.1</version>
				<scope>provided</scope>
			</dependency>`

**Comment by AntonySagar** [comment]
Guys,

I'm getting below error when upgrading AEM 6.1 to 6.2. I have added uber.jar dependency in POX xml. Does any have any ideas to resolve below error?

A required class was missing while executing org.apache.felix:maven-scr-plugin:1.20.0:scr: Lorg/apache/sling/settings/SlingSettingsService

Thanks,
Antony

**Comment by krassib** [comment]
@AntonySagar - can you share your uber.jar dependacy entries you put into pom.xml?

For me the following worked for AEM 6.2 SP1:
- in the parent pom.xml:
```
           <!-- Adobe 6.2 Uber Jar - needed for the WCMUsePojo -->
            <dependency>
                <groupId>com.adobe.aem</groupId>
                <artifactId>uber-jar</artifactId>
                <version>6.2.0-SP1</version>
                <scope>provided</scope>
                <classifier>apis</classifier>
            </dependency>

```
- in the bundle's pom.xml:
```
            <dependency>
                  <groupId>com.adobe.aem</groupId>
                  <artifactId>uber-jar</artifactId>
                  <classifier>apis</classifier>
            </dependency>
```

Thanks,
Krass

**Comment by AntonySagar** [comment]
This is how I have added in my project.

Parent pom.xml:
          <dependency>
				<groupId>com.adobe.aem</groupId>
				<artifactId>uber-jar</artifactId>
				<version>6.2.0</version>
				<classifier>obfuscated-apis</classifier>
				<scope>provided</scope>
			</dependency>

In child pom.xml's:
            <dependency>
				<groupId>com.adobe.aem</groupId>
				<artifactId>uber-jar</artifactId>
				<classifier>obfuscated-apis</classifier>
				<scope>provided</scope>
		</dependency>

Thanks
Sagar.

**Comment by AntonySagar** [comment]
This is how I have added in my project.

Parent pom.xml:
<dependency>
 <groupId>com.adobe.aem</groupId>
 <artifactId>uber-jar</artifactId>
 <version>6.2.0</version>
 <Classifier>obfuscated-apis<Classifier>
 <scope>provided</scope>
</dependency>

In child pom.xml's:

<dependency>
 <groupId>com.adobe.aem</groupId>
 <artifactId>uber-jar</artifactId>
 <Classifier>obfuscated-apis<Classifier>
 <scope>provided</scope>
</dependency>


Thanks
 Sagar.

**Comment by AntonySagar** [comment]
I have added the POM files like yours adding 6.2.0-SP1 version and classifier as apis. With this change I'm able to build the project successfully.

Is it mandatory that we have to give SP1?

Thanks,
Antony

**Comment by krassib** [comment]
SP1 classifier needs to be added, if you are going to be installing Service Pack 1.

For you reference, here is the maven repository for all Uber jar versions:
https://mvnrepository.com/artifact/com.adobe.aem/uber-jar

Cheers,
Krass

**Comment by AntonySagar** [comment]
Krassib, Thank you for the inputs and help.

Also any guideless are present or any mandatory checks we have to do to verify the code has been compiled and upgraded properly?

Thanks
Antony

**Comment by AntonySagar** [comment]
Hi Krassib,

I went to below path and seeing AEM version is 6.2.0 without SP1.  

http://localhost:4502/system/console/status-productinfo

Here I'm not sure why in POM XML I have to give 6.2.0-SP1 as version. If I give 6.2.0, I'm getting error. So any idea why we have to use the version as 6.2.0-SP1 even though my AEM setup in not on 6.2.0 SP1?

Thanks
Antony Sagar

**Comment by guptasuresh2004** [comment]
set environment varibale :
MAVEN_OPTS = -noverify

it worked for me.
